spring:
  datasource:
    url: jdbc:h2:mem:interestdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpadatabase-platform: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: create-drop

app:
  annual-interest: 5.00